GET http://localhost:3000/books/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjcyODMzMDE3fQ.MqG9S-IQoWoAjaqF4pjp5yVglmLtg4LYbd0bJOApkNQ


###

GET http://localhost:3000/books/1/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjcyODI5NjUxfQ.ZPNV4uu9lMxTuMOtVeY-CqnP8suaq88WWyKwQB5UsXQ

###

POST http://localhost:3000/users/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456",
    "gender":"male",
    "location":"hyderabad"
}

###

POST http://localhost:3000/login/
Content-Type: application/json

{    
    "username": "rahul123",
    "password": "rahul@456"
}

###


GET http://localhost:3000/profile/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhaHVsMTIzIiwiaWF0IjoxNjcyODM1OTE1fQ.jholRjl5ZtMh3YczLZrebYNlrti5Nbu--JHqTZlPW1I

###